#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: AthenaLockerTab

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "FortniteGame_structs.hpp"
#include "SlateCore_structs.hpp"
#include "CommonUI_structs.hpp"


namespace SDK::Params
{

// Function AthenaLockerTab.AthenaLockerTab_C.EnableSlotsForSTW
// 0x0018 (0x0018 - 0x0000)
struct AthenaLockerTab_C_EnableSlotsForSTW final
{
public:
	class UFortUINavigationManager*               CallFunc_GetUINavigationManager_ReturnValue;       // 0x0000(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class UFortRuntimeOptions*                    CallFunc_GetRuntimeOptions_ReturnValue;            // 0x0008(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	ESubGame                                      CallFunc_GetSubGame_ReturnValue;                   // 0x0010(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_EqualEqual_ByteByte_ReturnValue;          // 0x0011(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
};
static_assert(alignof(AthenaLockerTab_C_EnableSlotsForSTW) == 0x000008, "Wrong alignment on AthenaLockerTab_C_EnableSlotsForSTW");
static_assert(sizeof(AthenaLockerTab_C_EnableSlotsForSTW) == 0x000018, "Wrong size on AthenaLockerTab_C_EnableSlotsForSTW");
static_assert(offsetof(AthenaLockerTab_C_EnableSlotsForSTW, CallFunc_GetUINavigationManager_ReturnValue) == 0x000000, "Member 'AthenaLockerTab_C_EnableSlotsForSTW::CallFunc_GetUINavigationManager_ReturnValue' has a wrong offset!");
static_assert(offsetof(AthenaLockerTab_C_EnableSlotsForSTW, CallFunc_GetRuntimeOptions_ReturnValue) == 0x000008, "Member 'AthenaLockerTab_C_EnableSlotsForSTW::CallFunc_GetRuntimeOptions_ReturnValue' has a wrong offset!");
static_assert(offsetof(AthenaLockerTab_C_EnableSlotsForSTW, CallFunc_GetSubGame_ReturnValue) == 0x000010, "Member 'AthenaLockerTab_C_EnableSlotsForSTW::CallFunc_GetSubGame_ReturnValue' has a wrong offset!");
static_assert(offsetof(AthenaLockerTab_C_EnableSlotsForSTW, CallFunc_EqualEqual_ByteByte_ReturnValue) == 0x000011, "Member 'AthenaLockerTab_C_EnableSlotsForSTW::CallFunc_EqualEqual_ByteByte_ReturnValue' has a wrong offset!");

// Function AthenaLockerTab.AthenaLockerTab_C.OkToReshowOnHover
// 0x0038 (0x0038 - 0x0000)
struct AthenaLockerTab_C_OkToReshowOnHover final
{
public:
	EAthenaCustomizationCategory                  Type;                                              // 0x0000(0x0001)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_1[0x3];                                        // 0x0001(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	int32                                         Index_0;                                           // 0x0004(0x0004)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          Ok;                                                // 0x0008(0x0001)(Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          CallFunc_NotEqual_ByteByte_ReturnValue;            // 0x0009(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_A[0x6];                                        // 0x000A(0x0006)(Fixing Size After Last Property [ Dumper-7 ])
	class UFortFrontEndContext*                   CallFunc_GetContext_ReturnValue;                   // 0x0010(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class AFortPlayerPawn*                        CallFunc_GetHeroPlayerPawnForCurrentDisplayedItem_ReturnValue; // 0x0018(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_NotEqual_ByteByte_ReturnValue_1;          // 0x0020(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_21[0x7];                                       // 0x0021(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	class UAnimInstance*                          CallFunc_GetAnimInstance_ReturnValue;              // 0x0028(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_IsValid_ReturnValue;                      // 0x0030(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          CallFunc_IsAnyMontagePlaying_ReturnValue;          // 0x0031(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          CallFunc_Not_PreBool_ReturnValue;                  // 0x0032(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          CallFunc_NotEqual_IntInt_ReturnValue;              // 0x0033(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
};
static_assert(alignof(AthenaLockerTab_C_OkToReshowOnHover) == 0x000008, "Wrong alignment on AthenaLockerTab_C_OkToReshowOnHover");
static_assert(sizeof(AthenaLockerTab_C_OkToReshowOnHover) == 0x000038, "Wrong size on AthenaLockerTab_C_OkToReshowOnHover");
static_assert(offsetof(AthenaLockerTab_C_OkToReshowOnHover, Type) == 0x000000, "Member 'AthenaLockerTab_C_OkToReshowOnHover::Type' has a wrong offset!");
static_assert(offsetof(AthenaLockerTab_C_OkToReshowOnHover, Index_0) == 0x000004, "Member 'AthenaLockerTab_C_OkToReshowOnHover::Index_0' has a wrong offset!");
static_assert(offsetof(AthenaLockerTab_C_OkToReshowOnHover, Ok) == 0x000008, "Member 'AthenaLockerTab_C_OkToReshowOnHover::Ok' has a wrong offset!");
static_assert(offsetof(AthenaLockerTab_C_OkToReshowOnHover, CallFunc_NotEqual_ByteByte_ReturnValue) == 0x000009, "Member 'AthenaLockerTab_C_OkToReshowOnHover::CallFunc_NotEqual_ByteByte_ReturnValue' has a wrong offset!");
static_assert(offsetof(AthenaLockerTab_C_OkToReshowOnHover, CallFunc_GetContext_ReturnValue) == 0x000010, "Member 'AthenaLockerTab_C_OkToReshowOnHover::CallFunc_GetContext_ReturnValue' has a wrong offset!");
static_assert(offsetof(AthenaLockerTab_C_OkToReshowOnHover, CallFunc_GetHeroPlayerPawnForCurrentDisplayedItem_ReturnValue) == 0x000018, "Member 'AthenaLockerTab_C_OkToReshowOnHover::CallFunc_GetHeroPlayerPawnForCurrentDisplayedItem_ReturnValue' has a wrong offset!");
static_assert(offsetof(AthenaLockerTab_C_OkToReshowOnHover, CallFunc_NotEqual_ByteByte_ReturnValue_1) == 0x000020, "Member 'AthenaLockerTab_C_OkToReshowOnHover::CallFunc_NotEqual_ByteByte_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(AthenaLockerTab_C_OkToReshowOnHover, CallFunc_GetAnimInstance_ReturnValue) == 0x000028, "Member 'AthenaLockerTab_C_OkToReshowOnHover::CallFunc_GetAnimInstance_ReturnValue' has a wrong offset!");
static_assert(offsetof(AthenaLockerTab_C_OkToReshowOnHover, CallFunc_IsValid_ReturnValue) == 0x000030, "Member 'AthenaLockerTab_C_OkToReshowOnHover::CallFunc_IsValid_ReturnValue' has a wrong offset!");
static_assert(offsetof(AthenaLockerTab_C_OkToReshowOnHover, CallFunc_IsAnyMontagePlaying_ReturnValue) == 0x000031, "Member 'AthenaLockerTab_C_OkToReshowOnHover::CallFunc_IsAnyMontagePlaying_ReturnValue' has a wrong offset!");
static_assert(offsetof(AthenaLockerTab_C_OkToReshowOnHover, CallFunc_Not_PreBool_ReturnValue) == 0x000032, "Member 'AthenaLockerTab_C_OkToReshowOnHover::CallFunc_Not_PreBool_ReturnValue' has a wrong offset!");
static_assert(offsetof(AthenaLockerTab_C_OkToReshowOnHover, CallFunc_NotEqual_IntInt_ReturnValue) == 0x000033, "Member 'AthenaLockerTab_C_OkToReshowOnHover::CallFunc_NotEqual_IntInt_ReturnValue' has a wrong offset!");

// Function AthenaLockerTab.AthenaLockerTab_C.PlaySlotClickedAnimation
// 0x0010 (0x0010 - 0x0000)
struct AthenaLockerTab_C_PlaySlotClickedAnimation final
{
public:
	class UAthenaCustomizationSlotButton_C*       SlotToPlayAnimOn;                                  // 0x0000(0x0008)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class UUMGSequencePlayer*                     CallFunc_PlayAnimation_ReturnValue;                // 0x0008(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(AthenaLockerTab_C_PlaySlotClickedAnimation) == 0x000008, "Wrong alignment on AthenaLockerTab_C_PlaySlotClickedAnimation");
static_assert(sizeof(AthenaLockerTab_C_PlaySlotClickedAnimation) == 0x000010, "Wrong size on AthenaLockerTab_C_PlaySlotClickedAnimation");
static_assert(offsetof(AthenaLockerTab_C_PlaySlotClickedAnimation, SlotToPlayAnimOn) == 0x000000, "Member 'AthenaLockerTab_C_PlaySlotClickedAnimation::SlotToPlayAnimOn' has a wrong offset!");
static_assert(offsetof(AthenaLockerTab_C_PlaySlotClickedAnimation, CallFunc_PlayAnimation_ReturnValue) == 0x000008, "Member 'AthenaLockerTab_C_PlaySlotClickedAnimation::CallFunc_PlayAnimation_ReturnValue' has a wrong offset!");

// Function AthenaLockerTab.AthenaLockerTab_C.CanShowEmptyForType
// 0x0016 (0x0016 - 0x0000)
struct AthenaLockerTab_C_CanShowEmptyForType final
{
public:
	EAthenaCustomizationCategory                  CustomizationType;                                 // 0x0000(0x0001)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          bCanShowEmpty;                                     // 0x0001(0x0001)(Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor)
	EAthenaCustomizationCategory                  Temp_byte_Variable;                                // 0x0002(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          Temp_bool_Variable;                                // 0x0003(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          Temp_bool_Variable_1;                              // 0x0004(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          Temp_bool_Variable_2;                              // 0x0005(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          Temp_bool_Variable_3;                              // 0x0006(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          Temp_bool_Variable_4;                              // 0x0007(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          Temp_bool_Variable_5;                              // 0x0008(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          Temp_bool_Variable_6;                              // 0x0009(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          Temp_bool_Variable_7;                              // 0x000A(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          Temp_bool_Variable_8;                              // 0x000B(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          Temp_bool_Variable_9;                              // 0x000C(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          Temp_bool_Variable_10;                             // 0x000D(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          Temp_bool_Variable_11;                             // 0x000E(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          Temp_bool_Variable_12;                             // 0x000F(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          Temp_bool_Variable_13;                             // 0x0010(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          Temp_bool_Variable_14;                             // 0x0011(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          Temp_bool_Variable_15;                             // 0x0012(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          Temp_bool_Variable_16;                             // 0x0013(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          Temp_bool_Variable_17;                             // 0x0014(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          K2Node_Select_Default;                             // 0x0015(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
};
static_assert(alignof(AthenaLockerTab_C_CanShowEmptyForType) == 0x000001, "Wrong alignment on AthenaLockerTab_C_CanShowEmptyForType");
static_assert(sizeof(AthenaLockerTab_C_CanShowEmptyForType) == 0x000016, "Wrong size on AthenaLockerTab_C_CanShowEmptyForType");
static_assert(offsetof(AthenaLockerTab_C_CanShowEmptyForType, CustomizationType) == 0x000000, "Member 'AthenaLockerTab_C_CanShowEmptyForType::CustomizationType' has a wrong offset!");
static_assert(offsetof(AthenaLockerTab_C_CanShowEmptyForType, bCanShowEmpty) == 0x000001, "Member 'AthenaLockerTab_C_CanShowEmptyForType::bCanShowEmpty' has a wrong offset!");
static_assert(offsetof(AthenaLockerTab_C_CanShowEmptyForType, Temp_byte_Variable) == 0x000002, "Member 'AthenaLockerTab_C_CanShowEmptyForType::Temp_byte_Variable' has a wrong offset!");
static_assert(offsetof(AthenaLockerTab_C_CanShowEmptyForType, Temp_bool_Variable) == 0x000003, "Member 'AthenaLockerTab_C_CanShowEmptyForType::Temp_bool_Variable' has a wrong offset!");
static_assert(offsetof(AthenaLockerTab_C_CanShowEmptyForType, Temp_bool_Variable_1) == 0x000004, "Member 'AthenaLockerTab_C_CanShowEmptyForType::Temp_bool_Variable_1' has a wrong offset!");
static_assert(offsetof(AthenaLockerTab_C_CanShowEmptyForType, Temp_bool_Variable_2) == 0x000005, "Member 'AthenaLockerTab_C_CanShowEmptyForType::Temp_bool_Variable_2' has a wrong offset!");
static_assert(offsetof(AthenaLockerTab_C_CanShowEmptyForType, Temp_bool_Variable_3) == 0x000006, "Member 'AthenaLockerTab_C_CanShowEmptyForType::Temp_bool_Variable_3' has a wrong offset!");
static_assert(offsetof(AthenaLockerTab_C_CanShowEmptyForType, Temp_bool_Variable_4) == 0x000007, "Member 'AthenaLockerTab_C_CanShowEmptyForType::Temp_bool_Variable_4' has a wrong offset!");
static_assert(offsetof(AthenaLockerTab_C_CanShowEmptyForType, Temp_bool_Variable_5) == 0x000008, "Member 'AthenaLockerTab_C_CanShowEmptyForType::Temp_bool_Variable_5' has a wrong offset!");
static_assert(offsetof(AthenaLockerTab_C_CanShowEmptyForType, Temp_bool_Variable_6) == 0x000009, "Member 'AthenaLockerTab_C_CanShowEmptyForType::Temp_bool_Variable_6' has a wrong offset!");
static_assert(offsetof(AthenaLockerTab_C_CanShowEmptyForType, Temp_bool_Variable_7) == 0x00000A, "Member 'AthenaLockerTab_C_CanShowEmptyForType::Temp_bool_Variable_7' has a wrong offset!");
static_assert(offsetof(AthenaLockerTab_C_CanShowEmptyForType, Temp_bool_Variable_8) == 0x00000B, "Member 'AthenaLockerTab_C_CanShowEmptyForType::Temp_bool_Variable_8' has a wrong offset!");
static_assert(offsetof(AthenaLockerTab_C_CanShowEmptyForType, Temp_bool_Variable_9) == 0x00000C, "Member 'AthenaLockerTab_C_CanShowEmptyForType::Temp_bool_Variable_9' has a wrong offset!");
static_assert(offsetof(AthenaLockerTab_C_CanShowEmptyForType, Temp_bool_Variable_10) == 0x00000D, "Member 'AthenaLockerTab_C_CanShowEmptyForType::Temp_bool_Variable_10' has a wrong offset!");
static_assert(offsetof(AthenaLockerTab_C_CanShowEmptyForType, Temp_bool_Variable_11) == 0x00000E, "Member 'AthenaLockerTab_C_CanShowEmptyForType::Temp_bool_Variable_11' has a wrong offset!");
static_assert(offsetof(AthenaLockerTab_C_CanShowEmptyForType, Temp_bool_Variable_12) == 0x00000F, "Member 'AthenaLockerTab_C_CanShowEmptyForType::Temp_bool_Variable_12' has a wrong offset!");
static_assert(offsetof(AthenaLockerTab_C_CanShowEmptyForType, Temp_bool_Variable_13) == 0x000010, "Member 'AthenaLockerTab_C_CanShowEmptyForType::Temp_bool_Variable_13' has a wrong offset!");
static_assert(offsetof(AthenaLockerTab_C_CanShowEmptyForType, Temp_bool_Variable_14) == 0x000011, "Member 'AthenaLockerTab_C_CanShowEmptyForType::Temp_bool_Variable_14' has a wrong offset!");
static_assert(offsetof(AthenaLockerTab_C_CanShowEmptyForType, Temp_bool_Variable_15) == 0x000012, "Member 'AthenaLockerTab_C_CanShowEmptyForType::Temp_bool_Variable_15' has a wrong offset!");
static_assert(offsetof(AthenaLockerTab_C_CanShowEmptyForType, Temp_bool_Variable_16) == 0x000013, "Member 'AthenaLockerTab_C_CanShowEmptyForType::Temp_bool_Variable_16' has a wrong offset!");
static_assert(offsetof(AthenaLockerTab_C_CanShowEmptyForType, Temp_bool_Variable_17) == 0x000014, "Member 'AthenaLockerTab_C_CanShowEmptyForType::Temp_bool_Variable_17' has a wrong offset!");
static_assert(offsetof(AthenaLockerTab_C_CanShowEmptyForType, K2Node_Select_Default) == 0x000015, "Member 'AthenaLockerTab_C_CanShowEmptyForType::K2Node_Select_Default' has a wrong offset!");

// Function AthenaLockerTab.AthenaLockerTab_C.SelectWidget
// 0x0010 (0x0010 - 0x0000)
struct AthenaLockerTab_C_SelectWidget final
{
public:
	class UAthenaCustomizationSlotButtonWrapper_C* InSelection;                                       // 0x0000(0x0008)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class UFortUINavigationManager*               CallFunc_GetUINavigationManager_ReturnValue;       // 0x0008(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(AthenaLockerTab_C_SelectWidget) == 0x000008, "Wrong alignment on AthenaLockerTab_C_SelectWidget");
static_assert(sizeof(AthenaLockerTab_C_SelectWidget) == 0x000010, "Wrong size on AthenaLockerTab_C_SelectWidget");
static_assert(offsetof(AthenaLockerTab_C_SelectWidget, InSelection) == 0x000000, "Member 'AthenaLockerTab_C_SelectWidget::InSelection' has a wrong offset!");
static_assert(offsetof(AthenaLockerTab_C_SelectWidget, CallFunc_GetUINavigationManager_ReturnValue) == 0x000008, "Member 'AthenaLockerTab_C_SelectWidget::CallFunc_GetUINavigationManager_ReturnValue' has a wrong offset!");

// Function AthenaLockerTab.AthenaLockerTab_C.BeginPickingCustomization
// 0x0058 (0x0058 - 0x0000)
struct AthenaLockerTab_C_BeginPickingCustomization final
{
public:
	EAthenaCustomizationCategory                  Category;                                          // 0x0000(0x0001)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_1[0x7];                                        // 0x0001(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	class UCommonButton*                          WidgetToReturnFocusTo;                             // 0x0008(0x0008)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class FText                                   HeaderText;                                        // 0x0010(0x0018)(BlueprintVisible, BlueprintReadOnly, Parm)
	int32                                         Subslot_Index;                                     // 0x0028(0x0004)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_2C[0x4];                                       // 0x002C(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	class UUMGSequencePlayer*                     CallFunc_PlayAnimation_ReturnValue;                // 0x0030(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class UAthenaCustomizationSlotButton_C*       K2Node_DynamicCast_AsAthena_Customization_Slot_Button; // 0x0038(0x0008)(ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          K2Node_DynamicCast_bSuccess;                       // 0x0040(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_41[0x3];                                       // 0x0041(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	TDelegate<void()>                             K2Node_CreateDelegate_OutputDelegate;              // 0x0044(0x0010)(ZeroConstructor, NoDestructor)
};
static_assert(alignof(AthenaLockerTab_C_BeginPickingCustomization) == 0x000008, "Wrong alignment on AthenaLockerTab_C_BeginPickingCustomization");
static_assert(sizeof(AthenaLockerTab_C_BeginPickingCustomization) == 0x000058, "Wrong size on AthenaLockerTab_C_BeginPickingCustomization");
static_assert(offsetof(AthenaLockerTab_C_BeginPickingCustomization, Category) == 0x000000, "Member 'AthenaLockerTab_C_BeginPickingCustomization::Category' has a wrong offset!");
static_assert(offsetof(AthenaLockerTab_C_BeginPickingCustomization, WidgetToReturnFocusTo) == 0x000008, "Member 'AthenaLockerTab_C_BeginPickingCustomization::WidgetToReturnFocusTo' has a wrong offset!");
static_assert(offsetof(AthenaLockerTab_C_BeginPickingCustomization, HeaderText) == 0x000010, "Member 'AthenaLockerTab_C_BeginPickingCustomization::HeaderText' has a wrong offset!");
static_assert(offsetof(AthenaLockerTab_C_BeginPickingCustomization, Subslot_Index) == 0x000028, "Member 'AthenaLockerTab_C_BeginPickingCustomization::Subslot_Index' has a wrong offset!");
static_assert(offsetof(AthenaLockerTab_C_BeginPickingCustomization, CallFunc_PlayAnimation_ReturnValue) == 0x000030, "Member 'AthenaLockerTab_C_BeginPickingCustomization::CallFunc_PlayAnimation_ReturnValue' has a wrong offset!");
static_assert(offsetof(AthenaLockerTab_C_BeginPickingCustomization, K2Node_DynamicCast_AsAthena_Customization_Slot_Button) == 0x000038, "Member 'AthenaLockerTab_C_BeginPickingCustomization::K2Node_DynamicCast_AsAthena_Customization_Slot_Button' has a wrong offset!");
static_assert(offsetof(AthenaLockerTab_C_BeginPickingCustomization, K2Node_DynamicCast_bSuccess) == 0x000040, "Member 'AthenaLockerTab_C_BeginPickingCustomization::K2Node_DynamicCast_bSuccess' has a wrong offset!");
static_assert(offsetof(AthenaLockerTab_C_BeginPickingCustomization, K2Node_CreateDelegate_OutputDelegate) == 0x000044, "Member 'AthenaLockerTab_C_BeginPickingCustomization::K2Node_CreateDelegate_OutputDelegate' has a wrong offset!");

// Function AthenaLockerTab.AthenaLockerTab_C.HandleSlotClicked
// 0x0001 (0x0001 - 0x0000)
struct AthenaLockerTab_C_HandleSlotClicked final
{
public:
	bool                                          NewParam;                                          // 0x0000(0x0001)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor)
};
static_assert(alignof(AthenaLockerTab_C_HandleSlotClicked) == 0x000001, "Wrong alignment on AthenaLockerTab_C_HandleSlotClicked");
static_assert(sizeof(AthenaLockerTab_C_HandleSlotClicked) == 0x000001, "Wrong size on AthenaLockerTab_C_HandleSlotClicked");
static_assert(offsetof(AthenaLockerTab_C_HandleSlotClicked, NewParam) == 0x000000, "Member 'AthenaLockerTab_C_HandleSlotClicked::NewParam' has a wrong offset!");

// Function AthenaLockerTab.AthenaLockerTab_C.GetWidgetForFramingViewedItem
// 0x0008 (0x0008 - 0x0000)
struct AthenaLockerTab_C_GetWidgetForFramingViewedItem final
{
public:
	class UWidget*                                ReturnValue;                                       // 0x0000(0x0008)(Parm, OutParm, ZeroConstructor, ReturnParm, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(AthenaLockerTab_C_GetWidgetForFramingViewedItem) == 0x000008, "Wrong alignment on AthenaLockerTab_C_GetWidgetForFramingViewedItem");
static_assert(sizeof(AthenaLockerTab_C_GetWidgetForFramingViewedItem) == 0x000008, "Wrong size on AthenaLockerTab_C_GetWidgetForFramingViewedItem");
static_assert(offsetof(AthenaLockerTab_C_GetWidgetForFramingViewedItem, ReturnValue) == 0x000000, "Member 'AthenaLockerTab_C_GetWidgetForFramingViewedItem::ReturnValue' has a wrong offset!");

// Function AthenaLockerTab.AthenaLockerTab_C.SetItemDetailsToDisplay
// 0x0010 (0x0010 - 0x0000)
struct AthenaLockerTab_C_SetItemDetailsToDisplay final
{
public:
	class UFortItem*                              InputPin;                                          // 0x0000(0x0008)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_IsValid_ReturnValue;                      // 0x0008(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
};
static_assert(alignof(AthenaLockerTab_C_SetItemDetailsToDisplay) == 0x000008, "Wrong alignment on AthenaLockerTab_C_SetItemDetailsToDisplay");
static_assert(sizeof(AthenaLockerTab_C_SetItemDetailsToDisplay) == 0x000010, "Wrong size on AthenaLockerTab_C_SetItemDetailsToDisplay");
static_assert(offsetof(AthenaLockerTab_C_SetItemDetailsToDisplay, InputPin) == 0x000000, "Member 'AthenaLockerTab_C_SetItemDetailsToDisplay::InputPin' has a wrong offset!");
static_assert(offsetof(AthenaLockerTab_C_SetItemDetailsToDisplay, CallFunc_IsValid_ReturnValue) == 0x000008, "Member 'AthenaLockerTab_C_SetItemDetailsToDisplay::CallFunc_IsValid_ReturnValue' has a wrong offset!");

// Function AthenaLockerTab.AthenaLockerTab_C.ShowVaultItemByCategory
// 0x01A8 (0x01A8 - 0x0000)
struct AthenaLockerTab_C_ShowVaultItemByCategory final
{
public:
	EAthenaCustomizationCategory                  CustomizationType;                                 // 0x0000(0x0001)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_1[0x3];                                        // 0x0001(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	int32                                         SubslotIndex;                                      // 0x0004(0x0004)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CanShowEmpty;                                      // 0x0008(0x0001)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_9[0x7];                                        // 0x0009(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	class UFortItem*                              CallFunc_GetFavoriteItemForCategory_ReturnValue;   // 0x0010(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_EqualEqual_ByteByte_ReturnValue;          // 0x0018(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          CallFunc_IsValid_ReturnValue;                      // 0x0019(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_1A[0x6];                                       // 0x001A(0x0006)(Fixing Size After Last Property [ Dumper-7 ])
	class UFortItemDefinition*                    CallFunc_GetItemDefinitionBP_ReturnValue;          // 0x0020(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	ESubGame                                      CallFunc_GetSubGame_ReturnValue;                   // 0x0028(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_29[0x7];                                       // 0x0029(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	class UFortHomebaseUIContext*                 CallFunc_GetContext_ReturnValue;                   // 0x0030(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_EqualEqual_ByteByte_ReturnValue_1;        // 0x0038(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_39[0x7];                                       // 0x0039(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	class UFortHero*                              CallFunc_GetSlottedPrimaryHero_ReturnValue;        // 0x0040(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class UFortItemDefinition*                    CallFunc_GetItemDefinitionBP_ReturnValue_1;        // 0x0048(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class APlayerController*                      CallFunc_GetPlayerController_ReturnValue;          // 0x0050(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class UFortFrontEndContext*                   CallFunc_GetContext_ReturnValue_1;                 // 0x0058(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class AFortPlayerController*                  K2Node_DynamicCast_AsFort_Player_Controller;       // 0x0060(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          K2Node_DynamicCast_bSuccess;                       // 0x0068(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_69[0x7];                                       // 0x0069(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	struct FUniqueNetIdRepl                       CallFunc_GetGameAccountId_ReturnValue;             // 0x0070(0x0028)(HasGetValueTypeHash)
	class UFortMcpContext*                        CallFunc_GetContext_ReturnValue_2;                 // 0x0098(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class UFortFrontEndContext*                   CallFunc_GetContext_ReturnValue_3;                 // 0x00A0(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FFortAthenaLoadout                     CallFunc_GetLoadoutForPlayer_ReturnValue;          // 0x00A8(0x00D8)()
	class UFortMcpContext*                        CallFunc_GetContext_ReturnValue_4;                 // 0x0180(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class UFortMcpProfileAthena*                  CallFunc_GetAthenaProfile_ReturnValue;             // 0x0188(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class UAthenaCharacterItemDefinition*         CallFunc_GetRandomDefaultAthenaCharacterDefinition_ReturnValue; // 0x0190(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_IsValid_ReturnValue_1;                    // 0x0198(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_199[0x7];                                      // 0x0199(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	class UFortFrontEndContext*                   CallFunc_GetContext_ReturnValue_5;                 // 0x01A0(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(AthenaLockerTab_C_ShowVaultItemByCategory) == 0x000008, "Wrong alignment on AthenaLockerTab_C_ShowVaultItemByCategory");
static_assert(sizeof(AthenaLockerTab_C_ShowVaultItemByCategory) == 0x0001A8, "Wrong size on AthenaLockerTab_C_ShowVaultItemByCategory");
static_assert(offsetof(AthenaLockerTab_C_ShowVaultItemByCategory, CustomizationType) == 0x000000, "Member 'AthenaLockerTab_C_ShowVaultItemByCategory::CustomizationType' has a wrong offset!");
static_assert(offsetof(AthenaLockerTab_C_ShowVaultItemByCategory, SubslotIndex) == 0x000004, "Member 'AthenaLockerTab_C_ShowVaultItemByCategory::SubslotIndex' has a wrong offset!");
static_assert(offsetof(AthenaLockerTab_C_ShowVaultItemByCategory, CanShowEmpty) == 0x000008, "Member 'AthenaLockerTab_C_ShowVaultItemByCategory::CanShowEmpty' has a wrong offset!");
static_assert(offsetof(AthenaLockerTab_C_ShowVaultItemByCategory, CallFunc_GetFavoriteItemForCategory_ReturnValue) == 0x000010, "Member 'AthenaLockerTab_C_ShowVaultItemByCategory::CallFunc_GetFavoriteItemForCategory_ReturnValue' has a wrong offset!");
static_assert(offsetof(AthenaLockerTab_C_ShowVaultItemByCategory, CallFunc_EqualEqual_ByteByte_ReturnValue) == 0x000018, "Member 'AthenaLockerTab_C_ShowVaultItemByCategory::CallFunc_EqualEqual_ByteByte_ReturnValue' has a wrong offset!");
static_assert(offsetof(AthenaLockerTab_C_ShowVaultItemByCategory, CallFunc_IsValid_ReturnValue) == 0x000019, "Member 'AthenaLockerTab_C_ShowVaultItemByCategory::CallFunc_IsValid_ReturnValue' has a wrong offset!");
static_assert(offsetof(AthenaLockerTab_C_ShowVaultItemByCategory, CallFunc_GetItemDefinitionBP_ReturnValue) == 0x000020, "Member 'AthenaLockerTab_C_ShowVaultItemByCategory::CallFunc_GetItemDefinitionBP_ReturnValue' has a wrong offset!");
static_assert(offsetof(AthenaLockerTab_C_ShowVaultItemByCategory, CallFunc_GetSubGame_ReturnValue) == 0x000028, "Member 'AthenaLockerTab_C_ShowVaultItemByCategory::CallFunc_GetSubGame_ReturnValue' has a wrong offset!");
static_assert(offsetof(AthenaLockerTab_C_ShowVaultItemByCategory, CallFunc_GetContext_ReturnValue) == 0x000030, "Member 'AthenaLockerTab_C_ShowVaultItemByCategory::CallFunc_GetContext_ReturnValue' has a wrong offset!");
static_assert(offsetof(AthenaLockerTab_C_ShowVaultItemByCategory, CallFunc_EqualEqual_ByteByte_ReturnValue_1) == 0x000038, "Member 'AthenaLockerTab_C_ShowVaultItemByCategory::CallFunc_EqualEqual_ByteByte_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(AthenaLockerTab_C_ShowVaultItemByCategory, CallFunc_GetSlottedPrimaryHero_ReturnValue) == 0x000040, "Member 'AthenaLockerTab_C_ShowVaultItemByCategory::CallFunc_GetSlottedPrimaryHero_ReturnValue' has a wrong offset!");
static_assert(offsetof(AthenaLockerTab_C_ShowVaultItemByCategory, CallFunc_GetItemDefinitionBP_ReturnValue_1) == 0x000048, "Member 'AthenaLockerTab_C_ShowVaultItemByCategory::CallFunc_GetItemDefinitionBP_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(AthenaLockerTab_C_ShowVaultItemByCategory, CallFunc_GetPlayerController_ReturnValue) == 0x000050, "Member 'AthenaLockerTab_C_ShowVaultItemByCategory::CallFunc_GetPlayerController_ReturnValue' has a wrong offset!");
static_assert(offsetof(AthenaLockerTab_C_ShowVaultItemByCategory, CallFunc_GetContext_ReturnValue_1) == 0x000058, "Member 'AthenaLockerTab_C_ShowVaultItemByCategory::CallFunc_GetContext_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(AthenaLockerTab_C_ShowVaultItemByCategory, K2Node_DynamicCast_AsFort_Player_Controller) == 0x000060, "Member 'AthenaLockerTab_C_ShowVaultItemByCategory::K2Node_DynamicCast_AsFort_Player_Controller' has a wrong offset!");
static_assert(offsetof(AthenaLockerTab_C_ShowVaultItemByCategory, K2Node_DynamicCast_bSuccess) == 0x000068, "Member 'AthenaLockerTab_C_ShowVaultItemByCategory::K2Node_DynamicCast_bSuccess' has a wrong offset!");
static_assert(offsetof(AthenaLockerTab_C_ShowVaultItemByCategory, CallFunc_GetGameAccountId_ReturnValue) == 0x000070, "Member 'AthenaLockerTab_C_ShowVaultItemByCategory::CallFunc_GetGameAccountId_ReturnValue' has a wrong offset!");
static_assert(offsetof(AthenaLockerTab_C_ShowVaultItemByCategory, CallFunc_GetContext_ReturnValue_2) == 0x000098, "Member 'AthenaLockerTab_C_ShowVaultItemByCategory::CallFunc_GetContext_ReturnValue_2' has a wrong offset!");
static_assert(offsetof(AthenaLockerTab_C_ShowVaultItemByCategory, CallFunc_GetContext_ReturnValue_3) == 0x0000A0, "Member 'AthenaLockerTab_C_ShowVaultItemByCategory::CallFunc_GetContext_ReturnValue_3' has a wrong offset!");
static_assert(offsetof(AthenaLockerTab_C_ShowVaultItemByCategory, CallFunc_GetLoadoutForPlayer_ReturnValue) == 0x0000A8, "Member 'AthenaLockerTab_C_ShowVaultItemByCategory::CallFunc_GetLoadoutForPlayer_ReturnValue' has a wrong offset!");
static_assert(offsetof(AthenaLockerTab_C_ShowVaultItemByCategory, CallFunc_GetContext_ReturnValue_4) == 0x000180, "Member 'AthenaLockerTab_C_ShowVaultItemByCategory::CallFunc_GetContext_ReturnValue_4' has a wrong offset!");
static_assert(offsetof(AthenaLockerTab_C_ShowVaultItemByCategory, CallFunc_GetAthenaProfile_ReturnValue) == 0x000188, "Member 'AthenaLockerTab_C_ShowVaultItemByCategory::CallFunc_GetAthenaProfile_ReturnValue' has a wrong offset!");
static_assert(offsetof(AthenaLockerTab_C_ShowVaultItemByCategory, CallFunc_GetRandomDefaultAthenaCharacterDefinition_ReturnValue) == 0x000190, "Member 'AthenaLockerTab_C_ShowVaultItemByCategory::CallFunc_GetRandomDefaultAthenaCharacterDefinition_ReturnValue' has a wrong offset!");
static_assert(offsetof(AthenaLockerTab_C_ShowVaultItemByCategory, CallFunc_IsValid_ReturnValue_1) == 0x000198, "Member 'AthenaLockerTab_C_ShowVaultItemByCategory::CallFunc_IsValid_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(AthenaLockerTab_C_ShowVaultItemByCategory, CallFunc_GetContext_ReturnValue_5) == 0x0001A0, "Member 'AthenaLockerTab_C_ShowVaultItemByCategory::CallFunc_GetContext_ReturnValue_5' has a wrong offset!");

// Function AthenaLockerTab.AthenaLockerTab_C.HandleSlotHovered
// 0x00A0 (0x00A0 - 0x0000)
struct AthenaLockerTab_C_HandleSlotHovered final
{
public:
	EAthenaCustomizationCategory                  Type;                                              // 0x0000(0x0001)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_1[0x7];                                        // 0x0001(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	class FText                                   HeaderText;                                        // 0x0008(0x0018)(BlueprintVisible, BlueprintReadOnly, Parm)
	class FText                                   DescriptionText;                                   // 0x0020(0x0018)(BlueprintVisible, BlueprintReadOnly, Parm)
	int32                                         SubslotIndex;                                      // 0x0038(0x0004)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_3C[0x4];                                       // 0x003C(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	class UFortItem*                              CallFunc_GetFavoriteItemForCategory_ReturnValue;   // 0x0040(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_IsValid_ReturnValue;                      // 0x0048(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_49[0x7];                                       // 0x0049(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	class UFortItemDefinition*                    CallFunc_GetItemDefinitionBP_ReturnValue;          // 0x0050(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_K2_IsValidTimerHandle_ReturnValue;        // 0x0058(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          CallFunc_NotEqual_ByteByte_ReturnValue;            // 0x0059(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_5A[0x6];                                       // 0x005A(0x0006)(Fixing Size After Last Property [ Dumper-7 ])
	class FText                                   CallFunc_GetCategoryDisplayName_ReturnValue;       // 0x0060(0x0018)()
	TDelegate<void()>                             K2Node_CreateDelegate_OutputDelegate;              // 0x0078(0x0010)(ZeroConstructor, NoDestructor)
	struct FTimerHandle                           CallFunc_K2_SetTimerDelegate_ReturnValue;          // 0x0088(0x0008)(NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_OkToReshowOnHover_Ok;                     // 0x0090(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          CallFunc_CanShowEmptyForType_bCanShowEmpty;        // 0x0091(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_92[0x6];                                       // 0x0092(0x0006)(Fixing Size After Last Property [ Dumper-7 ])
	class UFortFrontEndContext*                   CallFunc_GetLocalPlayerSubsystem_ReturnValue;      // 0x0098(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(AthenaLockerTab_C_HandleSlotHovered) == 0x000008, "Wrong alignment on AthenaLockerTab_C_HandleSlotHovered");
static_assert(sizeof(AthenaLockerTab_C_HandleSlotHovered) == 0x0000A0, "Wrong size on AthenaLockerTab_C_HandleSlotHovered");
static_assert(offsetof(AthenaLockerTab_C_HandleSlotHovered, Type) == 0x000000, "Member 'AthenaLockerTab_C_HandleSlotHovered::Type' has a wrong offset!");
static_assert(offsetof(AthenaLockerTab_C_HandleSlotHovered, HeaderText) == 0x000008, "Member 'AthenaLockerTab_C_HandleSlotHovered::HeaderText' has a wrong offset!");
static_assert(offsetof(AthenaLockerTab_C_HandleSlotHovered, DescriptionText) == 0x000020, "Member 'AthenaLockerTab_C_HandleSlotHovered::DescriptionText' has a wrong offset!");
static_assert(offsetof(AthenaLockerTab_C_HandleSlotHovered, SubslotIndex) == 0x000038, "Member 'AthenaLockerTab_C_HandleSlotHovered::SubslotIndex' has a wrong offset!");
static_assert(offsetof(AthenaLockerTab_C_HandleSlotHovered, CallFunc_GetFavoriteItemForCategory_ReturnValue) == 0x000040, "Member 'AthenaLockerTab_C_HandleSlotHovered::CallFunc_GetFavoriteItemForCategory_ReturnValue' has a wrong offset!");
static_assert(offsetof(AthenaLockerTab_C_HandleSlotHovered, CallFunc_IsValid_ReturnValue) == 0x000048, "Member 'AthenaLockerTab_C_HandleSlotHovered::CallFunc_IsValid_ReturnValue' has a wrong offset!");
static_assert(offsetof(AthenaLockerTab_C_HandleSlotHovered, CallFunc_GetItemDefinitionBP_ReturnValue) == 0x000050, "Member 'AthenaLockerTab_C_HandleSlotHovered::CallFunc_GetItemDefinitionBP_ReturnValue' has a wrong offset!");
static_assert(offsetof(AthenaLockerTab_C_HandleSlotHovered, CallFunc_K2_IsValidTimerHandle_ReturnValue) == 0x000058, "Member 'AthenaLockerTab_C_HandleSlotHovered::CallFunc_K2_IsValidTimerHandle_ReturnValue' has a wrong offset!");
static_assert(offsetof(AthenaLockerTab_C_HandleSlotHovered, CallFunc_NotEqual_ByteByte_ReturnValue) == 0x000059, "Member 'AthenaLockerTab_C_HandleSlotHovered::CallFunc_NotEqual_ByteByte_ReturnValue' has a wrong offset!");
static_assert(offsetof(AthenaLockerTab_C_HandleSlotHovered, CallFunc_GetCategoryDisplayName_ReturnValue) == 0x000060, "Member 'AthenaLockerTab_C_HandleSlotHovered::CallFunc_GetCategoryDisplayName_ReturnValue' has a wrong offset!");
static_assert(offsetof(AthenaLockerTab_C_HandleSlotHovered, K2Node_CreateDelegate_OutputDelegate) == 0x000078, "Member 'AthenaLockerTab_C_HandleSlotHovered::K2Node_CreateDelegate_OutputDelegate' has a wrong offset!");
static_assert(offsetof(AthenaLockerTab_C_HandleSlotHovered, CallFunc_K2_SetTimerDelegate_ReturnValue) == 0x000088, "Member 'AthenaLockerTab_C_HandleSlotHovered::CallFunc_K2_SetTimerDelegate_ReturnValue' has a wrong offset!");
static_assert(offsetof(AthenaLockerTab_C_HandleSlotHovered, CallFunc_OkToReshowOnHover_Ok) == 0x000090, "Member 'AthenaLockerTab_C_HandleSlotHovered::CallFunc_OkToReshowOnHover_Ok' has a wrong offset!");
static_assert(offsetof(AthenaLockerTab_C_HandleSlotHovered, CallFunc_CanShowEmptyForType_bCanShowEmpty) == 0x000091, "Member 'AthenaLockerTab_C_HandleSlotHovered::CallFunc_CanShowEmptyForType_bCanShowEmpty' has a wrong offset!");
static_assert(offsetof(AthenaLockerTab_C_HandleSlotHovered, CallFunc_GetLocalPlayerSubsystem_ReturnValue) == 0x000098, "Member 'AthenaLockerTab_C_HandleSlotHovered::CallFunc_GetLocalPlayerSubsystem_ReturnValue' has a wrong offset!");

// Function AthenaLockerTab.AthenaLockerTab_C.SelectFirstWidget
// 0x0008 (0x0008 - 0x0000)
struct AthenaLockerTab_C_SelectFirstWidget final
{
public:
	class UFortUINavigationManager*               CallFunc_GetUINavigationManager_ReturnValue;       // 0x0000(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(AthenaLockerTab_C_SelectFirstWidget) == 0x000008, "Wrong alignment on AthenaLockerTab_C_SelectFirstWidget");
static_assert(sizeof(AthenaLockerTab_C_SelectFirstWidget) == 0x000008, "Wrong size on AthenaLockerTab_C_SelectFirstWidget");
static_assert(offsetof(AthenaLockerTab_C_SelectFirstWidget, CallFunc_GetUINavigationManager_ReturnValue) == 0x000000, "Member 'AthenaLockerTab_C_SelectFirstWidget::CallFunc_GetUINavigationManager_ReturnValue' has a wrong offset!");

// Function AthenaLockerTab.AthenaLockerTab_C.ShowSavingModal
// 0x00E0 (0x00E0 - 0x0000)
struct AthenaLockerTab_C_ShowSavingModal final
{
public:
	class UFortUIManagerWidget_NUI*               UIManager;                                         // 0x0000(0x0008)(Edit, BlueprintVisible, ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class FText                                   Temp_text_Variable;                                // 0x0008(0x0018)(ConstParm)
	class FText                                   Temp_text_Variable_1;                              // 0x0020(0x0018)(ConstParm)
	struct FSlateBrush                            CallFunc_NoResourceBrush_ReturnValue;              // 0x0038(0x0088)()
	bool                                          CallFunc_IsValid_ReturnValue;                      // 0x00C0(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_C1[0x7];                                       // 0x00C1(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	class APlayerController*                      CallFunc_GetOwningPlayer_ReturnValue;              // 0x00C8(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class UProgressModalWidget_C*                 CallFunc_Create_ReturnValue;                       // 0x00D0(0x0008)(ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class UFortUIManagerWidget_NUI*               CallFunc_GetUIManagerWidget_ReturnValue;           // 0x00D8(0x0008)(ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(AthenaLockerTab_C_ShowSavingModal) == 0x000008, "Wrong alignment on AthenaLockerTab_C_ShowSavingModal");
static_assert(sizeof(AthenaLockerTab_C_ShowSavingModal) == 0x0000E0, "Wrong size on AthenaLockerTab_C_ShowSavingModal");
static_assert(offsetof(AthenaLockerTab_C_ShowSavingModal, UIManager) == 0x000000, "Member 'AthenaLockerTab_C_ShowSavingModal::UIManager' has a wrong offset!");
static_assert(offsetof(AthenaLockerTab_C_ShowSavingModal, Temp_text_Variable) == 0x000008, "Member 'AthenaLockerTab_C_ShowSavingModal::Temp_text_Variable' has a wrong offset!");
static_assert(offsetof(AthenaLockerTab_C_ShowSavingModal, Temp_text_Variable_1) == 0x000020, "Member 'AthenaLockerTab_C_ShowSavingModal::Temp_text_Variable_1' has a wrong offset!");
static_assert(offsetof(AthenaLockerTab_C_ShowSavingModal, CallFunc_NoResourceBrush_ReturnValue) == 0x000038, "Member 'AthenaLockerTab_C_ShowSavingModal::CallFunc_NoResourceBrush_ReturnValue' has a wrong offset!");
static_assert(offsetof(AthenaLockerTab_C_ShowSavingModal, CallFunc_IsValid_ReturnValue) == 0x0000C0, "Member 'AthenaLockerTab_C_ShowSavingModal::CallFunc_IsValid_ReturnValue' has a wrong offset!");
static_assert(offsetof(AthenaLockerTab_C_ShowSavingModal, CallFunc_GetOwningPlayer_ReturnValue) == 0x0000C8, "Member 'AthenaLockerTab_C_ShowSavingModal::CallFunc_GetOwningPlayer_ReturnValue' has a wrong offset!");
static_assert(offsetof(AthenaLockerTab_C_ShowSavingModal, CallFunc_Create_ReturnValue) == 0x0000D0, "Member 'AthenaLockerTab_C_ShowSavingModal::CallFunc_Create_ReturnValue' has a wrong offset!");
static_assert(offsetof(AthenaLockerTab_C_ShowSavingModal, CallFunc_GetUIManagerWidget_ReturnValue) == 0x0000D8, "Member 'AthenaLockerTab_C_ShowSavingModal::CallFunc_GetUIManagerWidget_ReturnValue' has a wrong offset!");

// Function AthenaLockerTab.AthenaLockerTab_C.RefreshInputActions
// 0x0030 (0x0030 - 0x0000)
struct AthenaLockerTab_C_RefreshInputActions final
{
public:
	bool                                          Temp_bool_Variable;                                // 0x0000(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	EInputActionState                             Temp_byte_Variable;                                // 0x0001(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	EInputActionState                             Temp_byte_Variable_1;                              // 0x0002(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_IsMobileGame_ReturnValue;                 // 0x0003(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_4[0x4];                                        // 0x0004(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	struct FDataTableRowHandle                    K2Node_MakeStruct_DataTableRowHandle;              // 0x0008(0x0010)(NoDestructor)
	struct FDataTableRowHandle                    K2Node_MakeStruct_DataTableRowHandle_1;            // 0x0018(0x0010)(NoDestructor)
	EInputActionState                             K2Node_Select_Default;                             // 0x0028(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(AthenaLockerTab_C_RefreshInputActions) == 0x000008, "Wrong alignment on AthenaLockerTab_C_RefreshInputActions");
static_assert(sizeof(AthenaLockerTab_C_RefreshInputActions) == 0x000030, "Wrong size on AthenaLockerTab_C_RefreshInputActions");
static_assert(offsetof(AthenaLockerTab_C_RefreshInputActions, Temp_bool_Variable) == 0x000000, "Member 'AthenaLockerTab_C_RefreshInputActions::Temp_bool_Variable' has a wrong offset!");
static_assert(offsetof(AthenaLockerTab_C_RefreshInputActions, Temp_byte_Variable) == 0x000001, "Member 'AthenaLockerTab_C_RefreshInputActions::Temp_byte_Variable' has a wrong offset!");
static_assert(offsetof(AthenaLockerTab_C_RefreshInputActions, Temp_byte_Variable_1) == 0x000002, "Member 'AthenaLockerTab_C_RefreshInputActions::Temp_byte_Variable_1' has a wrong offset!");
static_assert(offsetof(AthenaLockerTab_C_RefreshInputActions, CallFunc_IsMobileGame_ReturnValue) == 0x000003, "Member 'AthenaLockerTab_C_RefreshInputActions::CallFunc_IsMobileGame_ReturnValue' has a wrong offset!");
static_assert(offsetof(AthenaLockerTab_C_RefreshInputActions, K2Node_MakeStruct_DataTableRowHandle) == 0x000008, "Member 'AthenaLockerTab_C_RefreshInputActions::K2Node_MakeStruct_DataTableRowHandle' has a wrong offset!");
static_assert(offsetof(AthenaLockerTab_C_RefreshInputActions, K2Node_MakeStruct_DataTableRowHandle_1) == 0x000018, "Member 'AthenaLockerTab_C_RefreshInputActions::K2Node_MakeStruct_DataTableRowHandle_1' has a wrong offset!");
static_assert(offsetof(AthenaLockerTab_C_RefreshInputActions, K2Node_Select_Default) == 0x000028, "Member 'AthenaLockerTab_C_RefreshInputActions::K2Node_Select_Default' has a wrong offset!");

// Function AthenaLockerTab.AthenaLockerTab_C.OnInputModeChanged
// 0x0001 (0x0001 - 0x0000)
struct AthenaLockerTab_C_OnInputModeChanged final
{
public:
	bool                                          bUsingGamepad;                                     // 0x0000(0x0001)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor)
};
static_assert(alignof(AthenaLockerTab_C_OnInputModeChanged) == 0x000001, "Wrong alignment on AthenaLockerTab_C_OnInputModeChanged");
static_assert(sizeof(AthenaLockerTab_C_OnInputModeChanged) == 0x000001, "Wrong size on AthenaLockerTab_C_OnInputModeChanged");
static_assert(offsetof(AthenaLockerTab_C_OnInputModeChanged, bUsingGamepad) == 0x000000, "Member 'AthenaLockerTab_C_OnInputModeChanged::bUsingGamepad' has a wrong offset!");

// Function AthenaLockerTab.AthenaLockerTab_C.BndEvt__AthenaCustomizationBannerButton_490_K2Node_ComponentBoundEvent_205_CommonButtonClicked__DelegateSignature
// 0x0008 (0x0008 - 0x0000)
struct AthenaLockerTab_C_BndEvt__AthenaCustomizationBannerButton_490_K2Node_ComponentBoundEvent_205_CommonButtonClicked__DelegateSignature final
{
public:
	class UCommonButton*                          Button;                                            // 0x0000(0x0008)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(AthenaLockerTab_C_BndEvt__AthenaCustomizationBannerButton_490_K2Node_ComponentBoundEvent_205_CommonButtonClicked__DelegateSignature) == 0x000008, "Wrong alignment on AthenaLockerTab_C_BndEvt__AthenaCustomizationBannerButton_490_K2Node_ComponentBoundEvent_205_CommonButtonClicked__DelegateSignature");
static_assert(sizeof(AthenaLockerTab_C_BndEvt__AthenaCustomizationBannerButton_490_K2Node_ComponentBoundEvent_205_CommonButtonClicked__DelegateSignature) == 0x000008, "Wrong size on AthenaLockerTab_C_BndEvt__AthenaCustomizationBannerButton_490_K2Node_ComponentBoundEvent_205_CommonButtonClicked__DelegateSignature");
static_assert(offsetof(AthenaLockerTab_C_BndEvt__AthenaCustomizationBannerButton_490_K2Node_ComponentBoundEvent_205_CommonButtonClicked__DelegateSignature, Button) == 0x000000, "Member 'AthenaLockerTab_C_BndEvt__AthenaCustomizationBannerButton_490_K2Node_ComponentBoundEvent_205_CommonButtonClicked__DelegateSignature::Button' has a wrong offset!");

// Function AthenaLockerTab.AthenaLockerTab_C.BndEvt__BannerSlot_K2Node_ComponentBoundEvent_547_CommonButtonClicked__DelegateSignature
// 0x0008 (0x0008 - 0x0000)
struct AthenaLockerTab_C_BndEvt__BannerSlot_K2Node_ComponentBoundEvent_547_CommonButtonClicked__DelegateSignature final
{
public:
	class UCommonButton*                          Button;                                            // 0x0000(0x0008)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(AthenaLockerTab_C_BndEvt__BannerSlot_K2Node_ComponentBoundEvent_547_CommonButtonClicked__DelegateSignature) == 0x000008, "Wrong alignment on AthenaLockerTab_C_BndEvt__BannerSlot_K2Node_ComponentBoundEvent_547_CommonButtonClicked__DelegateSignature");
static_assert(sizeof(AthenaLockerTab_C_BndEvt__BannerSlot_K2Node_ComponentBoundEvent_547_CommonButtonClicked__DelegateSignature) == 0x000008, "Wrong size on AthenaLockerTab_C_BndEvt__BannerSlot_K2Node_ComponentBoundEvent_547_CommonButtonClicked__DelegateSignature");
static_assert(offsetof(AthenaLockerTab_C_BndEvt__BannerSlot_K2Node_ComponentBoundEvent_547_CommonButtonClicked__DelegateSignature, Button) == 0x000000, "Member 'AthenaLockerTab_C_BndEvt__BannerSlot_K2Node_ComponentBoundEvent_547_CommonButtonClicked__DelegateSignature::Button' has a wrong offset!");

// Function AthenaLockerTab.AthenaLockerTab_C.ExecuteUbergraph_AthenaLockerTab
// 0x0160 (0x0160 - 0x0000)
struct AthenaLockerTab_C_ExecuteUbergraph_AthenaLockerTab final
{
public:
	int32                                         EntryPoint;                                        // 0x0000(0x0004)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         Temp_int_Variable;                                 // 0x0004(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         CallFunc_Add_IntInt_ReturnValue;                   // 0x0008(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          K2Node_Event_bUsingGamepad;                        // 0x000C(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_D[0x3];                                        // 0x000D(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	TDelegate<void(EAthenaCustomizationCategory CustomizationType, class FText BannerLabel, class FText CustomizationDescription, int32 SubslotIndex)> K2Node_CreateDelegate_OutputDelegate;              // 0x0010(0x0010)(ZeroConstructor, NoDestructor)
	int32                                         CallFunc_Array_Length_ReturnValue;                 // 0x0020(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         CallFunc_Array_Length_ReturnValue_1;               // 0x0024(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class APlayerController*                      CallFunc_GetOwningPlayer_ReturnValue;              // 0x0028(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class UAthenaItemCustomizationSelector_C*     CallFunc_Create_ReturnValue;                       // 0x0030(0x0008)(ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	TDelegate<void(EAthenaCustomizationCategory CustomizationType, class UCommonButton* Button, class FText BannerLabel, int32 Subslot_Index)> K2Node_CreateDelegate_OutputDelegate_1;            // 0x0038(0x0010)(ZeroConstructor, NoDestructor)
	class UFortUIManagerWidget_NUI*               CallFunc_GetUIManagerWidget_ReturnValue;           // 0x0048(0x0008)(ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class APlayerController*                      CallFunc_GetOwningPlayer_ReturnValue_1;            // 0x0050(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class UCommonButton*                          K2Node_ComponentBoundEvent_Button_1;               // 0x0058(0x0008)(ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class UAthenaBannerSelectModal_C*             CallFunc_Create_ReturnValue_1;                     // 0x0060(0x0008)(ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class UCommonButton*                          K2Node_ComponentBoundEvent_Button;                 // 0x0068(0x0008)(ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class UFortUIManagerWidget_NUI*               CallFunc_GetUIManagerWidget_ReturnValue_1;         // 0x0070(0x0008)(ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_IsMobileGame_ReturnValue;                 // 0x0078(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_79[0x3];                                       // 0x0079(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	int32                                         CallFunc_Array_Length_ReturnValue_2;               // 0x007C(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class UAthenaCustomizationSlotButtonWrapper_C* CallFunc_Array_Get_Item;                           // 0x0080(0x0008)(ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         CallFunc_Array_Length_ReturnValue_3;               // 0x0088(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_Less_IntInt_ReturnValue;                  // 0x008C(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_8D[0x3];                                       // 0x008D(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	int32                                         Temp_int_Variable_1;                               // 0x0090(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         CallFunc_Add_IntInt_ReturnValue_1;                 // 0x0094(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class UAthenaCustomizationSlotButtonWrapper_C* CallFunc_Array_Get_Item_1;                         // 0x0098(0x0008)(ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_Less_IntInt_ReturnValue_1;                // 0x00A0(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_A1[0x3];                                       // 0x00A1(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	int32                                         Temp_int_Variable_2;                               // 0x00A4(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         CallFunc_Add_IntInt_ReturnValue_2;                 // 0x00A8(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_AC[0x4];                                       // 0x00AC(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	class UAthenaCustomizationSlotButtonWrapper_C* CallFunc_Array_Get_Item_2;                         // 0x00B0(0x0008)(ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_Less_IntInt_ReturnValue_2;                // 0x00B8(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_B9[0x7];                                       // 0x00B9(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	class FText                                   CallFunc_GetItemTypeDisplayNames_ReturnValue;      // 0x00C0(0x0018)()
	class FText                                   CallFunc_GetCategoryDisplayName_ReturnValue;       // 0x00D8(0x0018)()
	bool                                          CallFunc_IsValid_ReturnValue;                      // 0x00F0(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_F1[0x7];                                       // 0x00F1(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	class UWidget*                                CallFunc_FindParentWidgetOfType_ReturnValue;       // 0x00F8(0x0008)(ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class UFortFrontEndContext*                   CallFunc_GetContext_ReturnValue;                   // 0x0100(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         CallFunc_GetEndTime_ReturnValue;                   // 0x0108(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_10C[0x4];                                      // 0x010C(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	class UUMGSequencePlayer*                     CallFunc_PlayAnimationTimeRange_ReturnValue;       // 0x0110(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         Temp_int_Variable_3;                               // 0x0118(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_11C[0x4];                                      // 0x011C(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	class UUMGSequencePlayer*                     CallFunc_PlayAnimationForward_ReturnValue;         // 0x0120(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         CallFunc_Add_IntInt_ReturnValue_3;                 // 0x0128(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_12C[0x4];                                      // 0x012C(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	class UAthenaCustomizationSlotButtonWrapper_C* CallFunc_Array_Get_Item_3;                         // 0x0130(0x0008)(ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_Less_IntInt_ReturnValue_3;                // 0x0138(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_139[0x7];                                      // 0x0139(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	class UFortUINavigationManager*               CallFunc_GetUINavigationManager_ReturnValue;       // 0x0140(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	TArray<class UAthenaCustomizationSlotButtonWrapper_C*> K2Node_MakeArray_Array;                            // 0x0148(0x0010)(ZeroConstructor, ReferenceParm)
	bool                                          CallFunc_K2_IsValidTimerHandle_ReturnValue;        // 0x0158(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	ESubGame                                      CallFunc_GetSubGame_ReturnValue;                   // 0x0159(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_EqualEqual_ByteByte_ReturnValue;          // 0x015A(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
};
static_assert(alignof(AthenaLockerTab_C_ExecuteUbergraph_AthenaLockerTab) == 0x000008, "Wrong alignment on AthenaLockerTab_C_ExecuteUbergraph_AthenaLockerTab");
static_assert(sizeof(AthenaLockerTab_C_ExecuteUbergraph_AthenaLockerTab) == 0x000160, "Wrong size on AthenaLockerTab_C_ExecuteUbergraph_AthenaLockerTab");
static_assert(offsetof(AthenaLockerTab_C_ExecuteUbergraph_AthenaLockerTab, EntryPoint) == 0x000000, "Member 'AthenaLockerTab_C_ExecuteUbergraph_AthenaLockerTab::EntryPoint' has a wrong offset!");
static_assert(offsetof(AthenaLockerTab_C_ExecuteUbergraph_AthenaLockerTab, Temp_int_Variable) == 0x000004, "Member 'AthenaLockerTab_C_ExecuteUbergraph_AthenaLockerTab::Temp_int_Variable' has a wrong offset!");
static_assert(offsetof(AthenaLockerTab_C_ExecuteUbergraph_AthenaLockerTab, CallFunc_Add_IntInt_ReturnValue) == 0x000008, "Member 'AthenaLockerTab_C_ExecuteUbergraph_AthenaLockerTab::CallFunc_Add_IntInt_ReturnValue' has a wrong offset!");
static_assert(offsetof(AthenaLockerTab_C_ExecuteUbergraph_AthenaLockerTab, K2Node_Event_bUsingGamepad) == 0x00000C, "Member 'AthenaLockerTab_C_ExecuteUbergraph_AthenaLockerTab::K2Node_Event_bUsingGamepad' has a wrong offset!");
static_assert(offsetof(AthenaLockerTab_C_ExecuteUbergraph_AthenaLockerTab, K2Node_CreateDelegate_OutputDelegate) == 0x000010, "Member 'AthenaLockerTab_C_ExecuteUbergraph_AthenaLockerTab::K2Node_CreateDelegate_OutputDelegate' has a wrong offset!");
static_assert(offsetof(AthenaLockerTab_C_ExecuteUbergraph_AthenaLockerTab, CallFunc_Array_Length_ReturnValue) == 0x000020, "Member 'AthenaLockerTab_C_ExecuteUbergraph_AthenaLockerTab::CallFunc_Array_Length_ReturnValue' has a wrong offset!");
static_assert(offsetof(AthenaLockerTab_C_ExecuteUbergraph_AthenaLockerTab, CallFunc_Array_Length_ReturnValue_1) == 0x000024, "Member 'AthenaLockerTab_C_ExecuteUbergraph_AthenaLockerTab::CallFunc_Array_Length_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(AthenaLockerTab_C_ExecuteUbergraph_AthenaLockerTab, CallFunc_GetOwningPlayer_ReturnValue) == 0x000028, "Member 'AthenaLockerTab_C_ExecuteUbergraph_AthenaLockerTab::CallFunc_GetOwningPlayer_ReturnValue' has a wrong offset!");
static_assert(offsetof(AthenaLockerTab_C_ExecuteUbergraph_AthenaLockerTab, CallFunc_Create_ReturnValue) == 0x000030, "Member 'AthenaLockerTab_C_ExecuteUbergraph_AthenaLockerTab::CallFunc_Create_ReturnValue' has a wrong offset!");
static_assert(offsetof(AthenaLockerTab_C_ExecuteUbergraph_AthenaLockerTab, K2Node_CreateDelegate_OutputDelegate_1) == 0x000038, "Member 'AthenaLockerTab_C_ExecuteUbergraph_AthenaLockerTab::K2Node_CreateDelegate_OutputDelegate_1' has a wrong offset!");
static_assert(offsetof(AthenaLockerTab_C_ExecuteUbergraph_AthenaLockerTab, CallFunc_GetUIManagerWidget_ReturnValue) == 0x000048, "Member 'AthenaLockerTab_C_ExecuteUbergraph_AthenaLockerTab::CallFunc_GetUIManagerWidget_ReturnValue' has a wrong offset!");
static_assert(offsetof(AthenaLockerTab_C_ExecuteUbergraph_AthenaLockerTab, CallFunc_GetOwningPlayer_ReturnValue_1) == 0x000050, "Member 'AthenaLockerTab_C_ExecuteUbergraph_AthenaLockerTab::CallFunc_GetOwningPlayer_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(AthenaLockerTab_C_ExecuteUbergraph_AthenaLockerTab, K2Node_ComponentBoundEvent_Button_1) == 0x000058, "Member 'AthenaLockerTab_C_ExecuteUbergraph_AthenaLockerTab::K2Node_ComponentBoundEvent_Button_1' has a wrong offset!");
static_assert(offsetof(AthenaLockerTab_C_ExecuteUbergraph_AthenaLockerTab, CallFunc_Create_ReturnValue_1) == 0x000060, "Member 'AthenaLockerTab_C_ExecuteUbergraph_AthenaLockerTab::CallFunc_Create_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(AthenaLockerTab_C_ExecuteUbergraph_AthenaLockerTab, K2Node_ComponentBoundEvent_Button) == 0x000068, "Member 'AthenaLockerTab_C_ExecuteUbergraph_AthenaLockerTab::K2Node_ComponentBoundEvent_Button' has a wrong offset!");
static_assert(offsetof(AthenaLockerTab_C_ExecuteUbergraph_AthenaLockerTab, CallFunc_GetUIManagerWidget_ReturnValue_1) == 0x000070, "Member 'AthenaLockerTab_C_ExecuteUbergraph_AthenaLockerTab::CallFunc_GetUIManagerWidget_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(AthenaLockerTab_C_ExecuteUbergraph_AthenaLockerTab, CallFunc_IsMobileGame_ReturnValue) == 0x000078, "Member 'AthenaLockerTab_C_ExecuteUbergraph_AthenaLockerTab::CallFunc_IsMobileGame_ReturnValue' has a wrong offset!");
static_assert(offsetof(AthenaLockerTab_C_ExecuteUbergraph_AthenaLockerTab, CallFunc_Array_Length_ReturnValue_2) == 0x00007C, "Member 'AthenaLockerTab_C_ExecuteUbergraph_AthenaLockerTab::CallFunc_Array_Length_ReturnValue_2' has a wrong offset!");
static_assert(offsetof(AthenaLockerTab_C_ExecuteUbergraph_AthenaLockerTab, CallFunc_Array_Get_Item) == 0x000080, "Member 'AthenaLockerTab_C_ExecuteUbergraph_AthenaLockerTab::CallFunc_Array_Get_Item' has a wrong offset!");
static_assert(offsetof(AthenaLockerTab_C_ExecuteUbergraph_AthenaLockerTab, CallFunc_Array_Length_ReturnValue_3) == 0x000088, "Member 'AthenaLockerTab_C_ExecuteUbergraph_AthenaLockerTab::CallFunc_Array_Length_ReturnValue_3' has a wrong offset!");
static_assert(offsetof(AthenaLockerTab_C_ExecuteUbergraph_AthenaLockerTab, CallFunc_Less_IntInt_ReturnValue) == 0x00008C, "Member 'AthenaLockerTab_C_ExecuteUbergraph_AthenaLockerTab::CallFunc_Less_IntInt_ReturnValue' has a wrong offset!");
static_assert(offsetof(AthenaLockerTab_C_ExecuteUbergraph_AthenaLockerTab, Temp_int_Variable_1) == 0x000090, "Member 'AthenaLockerTab_C_ExecuteUbergraph_AthenaLockerTab::Temp_int_Variable_1' has a wrong offset!");
static_assert(offsetof(AthenaLockerTab_C_ExecuteUbergraph_AthenaLockerTab, CallFunc_Add_IntInt_ReturnValue_1) == 0x000094, "Member 'AthenaLockerTab_C_ExecuteUbergraph_AthenaLockerTab::CallFunc_Add_IntInt_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(AthenaLockerTab_C_ExecuteUbergraph_AthenaLockerTab, CallFunc_Array_Get_Item_1) == 0x000098, "Member 'AthenaLockerTab_C_ExecuteUbergraph_AthenaLockerTab::CallFunc_Array_Get_Item_1' has a wrong offset!");
static_assert(offsetof(AthenaLockerTab_C_ExecuteUbergraph_AthenaLockerTab, CallFunc_Less_IntInt_ReturnValue_1) == 0x0000A0, "Member 'AthenaLockerTab_C_ExecuteUbergraph_AthenaLockerTab::CallFunc_Less_IntInt_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(AthenaLockerTab_C_ExecuteUbergraph_AthenaLockerTab, Temp_int_Variable_2) == 0x0000A4, "Member 'AthenaLockerTab_C_ExecuteUbergraph_AthenaLockerTab::Temp_int_Variable_2' has a wrong offset!");
static_assert(offsetof(AthenaLockerTab_C_ExecuteUbergraph_AthenaLockerTab, CallFunc_Add_IntInt_ReturnValue_2) == 0x0000A8, "Member 'AthenaLockerTab_C_ExecuteUbergraph_AthenaLockerTab::CallFunc_Add_IntInt_ReturnValue_2' has a wrong offset!");
static_assert(offsetof(AthenaLockerTab_C_ExecuteUbergraph_AthenaLockerTab, CallFunc_Array_Get_Item_2) == 0x0000B0, "Member 'AthenaLockerTab_C_ExecuteUbergraph_AthenaLockerTab::CallFunc_Array_Get_Item_2' has a wrong offset!");
static_assert(offsetof(AthenaLockerTab_C_ExecuteUbergraph_AthenaLockerTab, CallFunc_Less_IntInt_ReturnValue_2) == 0x0000B8, "Member 'AthenaLockerTab_C_ExecuteUbergraph_AthenaLockerTab::CallFunc_Less_IntInt_ReturnValue_2' has a wrong offset!");
static_assert(offsetof(AthenaLockerTab_C_ExecuteUbergraph_AthenaLockerTab, CallFunc_GetItemTypeDisplayNames_ReturnValue) == 0x0000C0, "Member 'AthenaLockerTab_C_ExecuteUbergraph_AthenaLockerTab::CallFunc_GetItemTypeDisplayNames_ReturnValue' has a wrong offset!");
static_assert(offsetof(AthenaLockerTab_C_ExecuteUbergraph_AthenaLockerTab, CallFunc_GetCategoryDisplayName_ReturnValue) == 0x0000D8, "Member 'AthenaLockerTab_C_ExecuteUbergraph_AthenaLockerTab::CallFunc_GetCategoryDisplayName_ReturnValue' has a wrong offset!");
static_assert(offsetof(AthenaLockerTab_C_ExecuteUbergraph_AthenaLockerTab, CallFunc_IsValid_ReturnValue) == 0x0000F0, "Member 'AthenaLockerTab_C_ExecuteUbergraph_AthenaLockerTab::CallFunc_IsValid_ReturnValue' has a wrong offset!");
static_assert(offsetof(AthenaLockerTab_C_ExecuteUbergraph_AthenaLockerTab, CallFunc_FindParentWidgetOfType_ReturnValue) == 0x0000F8, "Member 'AthenaLockerTab_C_ExecuteUbergraph_AthenaLockerTab::CallFunc_FindParentWidgetOfType_ReturnValue' has a wrong offset!");
static_assert(offsetof(AthenaLockerTab_C_ExecuteUbergraph_AthenaLockerTab, CallFunc_GetContext_ReturnValue) == 0x000100, "Member 'AthenaLockerTab_C_ExecuteUbergraph_AthenaLockerTab::CallFunc_GetContext_ReturnValue' has a wrong offset!");
static_assert(offsetof(AthenaLockerTab_C_ExecuteUbergraph_AthenaLockerTab, CallFunc_GetEndTime_ReturnValue) == 0x000108, "Member 'AthenaLockerTab_C_ExecuteUbergraph_AthenaLockerTab::CallFunc_GetEndTime_ReturnValue' has a wrong offset!");
static_assert(offsetof(AthenaLockerTab_C_ExecuteUbergraph_AthenaLockerTab, CallFunc_PlayAnimationTimeRange_ReturnValue) == 0x000110, "Member 'AthenaLockerTab_C_ExecuteUbergraph_AthenaLockerTab::CallFunc_PlayAnimationTimeRange_ReturnValue' has a wrong offset!");
static_assert(offsetof(AthenaLockerTab_C_ExecuteUbergraph_AthenaLockerTab, Temp_int_Variable_3) == 0x000118, "Member 'AthenaLockerTab_C_ExecuteUbergraph_AthenaLockerTab::Temp_int_Variable_3' has a wrong offset!");
static_assert(offsetof(AthenaLockerTab_C_ExecuteUbergraph_AthenaLockerTab, CallFunc_PlayAnimationForward_ReturnValue) == 0x000120, "Member 'AthenaLockerTab_C_ExecuteUbergraph_AthenaLockerTab::CallFunc_PlayAnimationForward_ReturnValue' has a wrong offset!");
static_assert(offsetof(AthenaLockerTab_C_ExecuteUbergraph_AthenaLockerTab, CallFunc_Add_IntInt_ReturnValue_3) == 0x000128, "Member 'AthenaLockerTab_C_ExecuteUbergraph_AthenaLockerTab::CallFunc_Add_IntInt_ReturnValue_3' has a wrong offset!");
static_assert(offsetof(AthenaLockerTab_C_ExecuteUbergraph_AthenaLockerTab, CallFunc_Array_Get_Item_3) == 0x000130, "Member 'AthenaLockerTab_C_ExecuteUbergraph_AthenaLockerTab::CallFunc_Array_Get_Item_3' has a wrong offset!");
static_assert(offsetof(AthenaLockerTab_C_ExecuteUbergraph_AthenaLockerTab, CallFunc_Less_IntInt_ReturnValue_3) == 0x000138, "Member 'AthenaLockerTab_C_ExecuteUbergraph_AthenaLockerTab::CallFunc_Less_IntInt_ReturnValue_3' has a wrong offset!");
static_assert(offsetof(AthenaLockerTab_C_ExecuteUbergraph_AthenaLockerTab, CallFunc_GetUINavigationManager_ReturnValue) == 0x000140, "Member 'AthenaLockerTab_C_ExecuteUbergraph_AthenaLockerTab::CallFunc_GetUINavigationManager_ReturnValue' has a wrong offset!");
static_assert(offsetof(AthenaLockerTab_C_ExecuteUbergraph_AthenaLockerTab, K2Node_MakeArray_Array) == 0x000148, "Member 'AthenaLockerTab_C_ExecuteUbergraph_AthenaLockerTab::K2Node_MakeArray_Array' has a wrong offset!");
static_assert(offsetof(AthenaLockerTab_C_ExecuteUbergraph_AthenaLockerTab, CallFunc_K2_IsValidTimerHandle_ReturnValue) == 0x000158, "Member 'AthenaLockerTab_C_ExecuteUbergraph_AthenaLockerTab::CallFunc_K2_IsValidTimerHandle_ReturnValue' has a wrong offset!");
static_assert(offsetof(AthenaLockerTab_C_ExecuteUbergraph_AthenaLockerTab, CallFunc_GetSubGame_ReturnValue) == 0x000159, "Member 'AthenaLockerTab_C_ExecuteUbergraph_AthenaLockerTab::CallFunc_GetSubGame_ReturnValue' has a wrong offset!");
static_assert(offsetof(AthenaLockerTab_C_ExecuteUbergraph_AthenaLockerTab, CallFunc_EqualEqual_ByteByte_ReturnValue) == 0x00015A, "Member 'AthenaLockerTab_C_ExecuteUbergraph_AthenaLockerTab::CallFunc_EqualEqual_ByteByte_ReturnValue' has a wrong offset!");

}

