#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_SolarisPrototype

#include "Basic.hpp"

#include "FortniteGame_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass BP_SolarisPrototype.BP_SolarisPrototype_C
// 0x0008 (0x0248 - 0x0240)
class ABP_SolarisPrototype_C final : public ASolarisPrototype
{
public:
	class USceneComponent*                        DefaultSceneRoot;                                  // 0x0240(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, IsPlainOldData, NonTransactional, NoDestructor, HasGetValueTypeHash)

public:
	struct FSolarisResponse CheckEndConditions();

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"BP_SolarisPrototype_C">();
	}
	static class ABP_SolarisPrototype_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<ABP_SolarisPrototype_C>();
	}
};
static_assert(alignof(ABP_SolarisPrototype_C) == 0x000008, "Wrong alignment on ABP_SolarisPrototype_C");
static_assert(sizeof(ABP_SolarisPrototype_C) == 0x000248, "Wrong size on ABP_SolarisPrototype_C");
static_assert(offsetof(ABP_SolarisPrototype_C, DefaultSceneRoot) == 0x000240, "Member 'ABP_SolarisPrototype_C::DefaultSceneRoot' has a wrong offset!");

}

