#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: CandleSingle

#include "Basic.hpp"

#include "Parent_BuildingPropActor_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass CandleSingle.CandleSingle_C
// 0x0010 (0x0BF0 - 0x0BE0)
class ACandleSingle_C final : public AParent_BuildingPropActor_C
{
public:
	class UStaticMeshComponent*                   SM_FlameShape;                                     // 0x0BE0(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, IsPlainOldData, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class UPointLightComponent*                   PointLight;                                        // 0x0BE8(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, IsPlainOldData, NonTransactional, NoDestructor, HasGetValueTypeHash)

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"CandleSingle_C">();
	}
	static class ACandleSingle_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<ACandleSingle_C>();
	}
};
static_assert(alignof(ACandleSingle_C) == 0x000008, "Wrong alignment on ACandleSingle_C");
static_assert(sizeof(ACandleSingle_C) == 0x000BF0, "Wrong size on ACandleSingle_C");
static_assert(offsetof(ACandleSingle_C, SM_FlameShape) == 0x000BE0, "Member 'ACandleSingle_C::SM_FlameShape' has a wrong offset!");
static_assert(offsetof(ACandleSingle_C, PointLight) == 0x000BE8, "Member 'ACandleSingle_C::PointLight' has a wrong offset!");

}

