#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: AccountPinLinkingWindow

#include "Basic.hpp"

#include "FortniteUI_classes.hpp"


namespace SDK
{

// WidgetBlueprintGeneratedClass AccountPinLinkingWindow.AccountPinLinkingWindow_C
// 0x0010 (0x0470 - 0x0460)
class UAccountPinLinkingWindow_C final : public UFortAccountPinLinkingWindow
{
public:
	class UCommonRichTextBlock*                   CommonRichTextBlock_84;                            // 0x0460(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UImage*                                 Image_83;                                          // 0x0468(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"AccountPinLinkingWindow_C">();
	}
	static class UAccountPinLinkingWindow_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UAccountPinLinkingWindow_C>();
	}
};
static_assert(alignof(UAccountPinLinkingWindow_C) == 0x000008, "Wrong alignment on UAccountPinLinkingWindow_C");
static_assert(sizeof(UAccountPinLinkingWindow_C) == 0x000470, "Wrong size on UAccountPinLinkingWindow_C");
static_assert(offsetof(UAccountPinLinkingWindow_C, CommonRichTextBlock_84) == 0x000460, "Member 'UAccountPinLinkingWindow_C::CommonRichTextBlock_84' has a wrong offset!");
static_assert(offsetof(UAccountPinLinkingWindow_C, Image_83) == 0x000468, "Member 'UAccountPinLinkingWindow_C::Image_83' has a wrong offset!");

}

