#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: ActivatableMovieWidget

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "FortniteUI_classes.hpp"


namespace SDK
{

// WidgetBlueprintGeneratedClass ActivatableMovieWidget.ActivatableMovieWidget_C
// 0x0008 (0x03A8 - 0x03A0)
class UActivatableMovieWidget_C final : public UFortActivatableVideoPanel
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x03A0(0x0008)(ZeroConstructor, Transient, DuplicateTransient)

public:
	void OnDeactivated();
	void OnActivated();
	void ExecuteUbergraph_ActivatableMovieWidget(int32 EntryPoint);

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"ActivatableMovieWidget_C">();
	}
	static class UActivatableMovieWidget_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UActivatableMovieWidget_C>();
	}
};
static_assert(alignof(UActivatableMovieWidget_C) == 0x000008, "Wrong alignment on UActivatableMovieWidget_C");
static_assert(sizeof(UActivatableMovieWidget_C) == 0x0003A8, "Wrong size on UActivatableMovieWidget_C");
static_assert(offsetof(UActivatableMovieWidget_C, UberGraphFrame) == 0x0003A0, "Member 'UActivatableMovieWidget_C::UberGraphFrame' has a wrong offset!");

}

