#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: Announce_LowHeath

#include "Basic.hpp"

#include "FortniteGame_classes.hpp"
#include "Engine_structs.hpp"


namespace SDK
{

// BlueprintGeneratedClass Announce_LowHeath.Announce_LowHeath_C
// 0x0010 (0x03A8 - 0x0398)
class AAnnounce_LowHeath_C final : public AFortClientAnnouncement_Basic
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x0398(0x0008)(ZeroConstructor, Transient, DuplicateTransient)
	class USceneComponent*                        DefaultSceneRoot;                                  // 0x03A0(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, IsPlainOldData, NonTransactional, NoDestructor, HasGetValueTypeHash)

public:
	void ExecuteUbergraph_Announce_LowHeath(int32 EntryPoint);
	void OnClientAnnouncementStart();

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"Announce_LowHeath_C">();
	}
	static class AAnnounce_LowHeath_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<AAnnounce_LowHeath_C>();
	}
};
static_assert(alignof(AAnnounce_LowHeath_C) == 0x000008, "Wrong alignment on AAnnounce_LowHeath_C");
static_assert(sizeof(AAnnounce_LowHeath_C) == 0x0003A8, "Wrong size on AAnnounce_LowHeath_C");
static_assert(offsetof(AAnnounce_LowHeath_C, UberGraphFrame) == 0x000398, "Member 'AAnnounce_LowHeath_C::UberGraphFrame' has a wrong offset!");
static_assert(offsetof(AAnnounce_LowHeath_C, DefaultSceneRoot) == 0x0003A0, "Member 'AAnnounce_LowHeath_C::DefaultSceneRoot' has a wrong offset!");

}

